openapi: 3.0.0
info:
  title: Utilities for Signalk
  version: 1.0.0
servers:
  - url: http://localhost:3000

paths:
  /sendmail:
    post:
      summary: Send an email via Nodemailer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to: 
                  type: string
                  description: Recipient email address
                subject:
                  type: string
                  description: Email subject
                text:
                  type: string
                  description: Plain text email body
                html:
                  type: string
                  description: HTML email body (optional)
      responses:
        '200':
          description: Email sent successfully
        '400':
          description: Bad request (e.g., missing required fields)
        '500':
          description: Internal server error (e.g., Nodemailer configuration issue)
